# Generated by Django 3.1 on 2020-08-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceuser',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='conferenceuser',
            old_name='poster_id',
            new_name='poster',
        ),
    ]
