# Generated by Django 3.1 on 2020-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='paper/')),
            ],
        ),
    ]
