# Generated by Django 3.1 on 2020-08-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSub', '0002_remove_paper_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(null=True, upload_to='papers/'),
        ),
    ]
