# Generated by Django 3.1 on 2020-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSub', '0003_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
