# Generated by Django 3.1 on 2020-08-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSub', '0004_auto_20200830_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
