# Generated by Django 3.1 on 2020-08-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosterSub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
